version: '3.1'

services:
  db:
    container_name: econox_db
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306

  phpmyadmin:
    container_name: econox_phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    depends_on:
      - db